import { getDayName } from "../utils/forecast";

export const defaultData = (() => {
  var date = new Date();
  const getDate = (offset: number) => {
    return `${getDayName((date.getDay() + offset) % 7)}, ${date.getDate() + offset}.${(date.getMonth() + 1).toString().padStart(2, "0")}`;
  };
  return [
    {
      time: getDate(0),
      temp_max: 0.8,
      temp_min: -3.9,
      precip_sum: 0,
      rain: 0,
      showers: 0,
      snow: 0,
      wind_speed: 10.9,
      wind_gusts: 24.5,
      wind_dir: 185,
    },
    {
      time: getDate(1),
      temp_max: 1.2,
      temp_min: -2.1,
      precip_sum: 0.4,
      rain: 0,
      showers: 0,
      snow: 0.28,
      wind_speed: 6.6,
      wind_gusts: 14,
      wind_dir: 266,
    },
    {
      time: getDate(2),
      temp_max: 1.9,
      temp_min: -1.6,
      precip_sum: 1,
      rain: 0.9,
      showers: 0,
      snow: 0.07,
      wind_speed: 19.4,
      wind_gusts: 45.7,
      wind_dir: 342,
    },
    {
      time: getDate(3),
      temp_max: 1.3,
      temp_min: -0.2,
      precip_sum: 5.6,
      rain: 3.2,
      showers: 0,
      snow: 1.47,
      wind_speed: 13,
      wind_gusts: 31.7,
      wind_dir: 37,
    },
    {
      time: getDate(4),
      temp_max: 1,
      temp_min: -0.2,
      precip_sum: 1.5,
      rain: 0,
      showers: 0,
      snow: 1.05,
      wind_speed: 6.2,
      wind_gusts: 14,
      wind_dir: 40,
    },
    {
      time: getDate(5),
      temp_max: 0.9,
      temp_min: -0.2,
      precip_sum: 3.5,
      rain: 0,
      showers: 3.5,
      snow: 0,
      wind_speed: 4.8,
      wind_gusts: 11.5,
      wind_dir: 358,
    },
    {
      time: getDate(6),
      temp_max: 1.9,
      temp_min: -0.3,
      precip_sum: 0.3,
      rain: 0.3,
      showers: 0,
      snow: 0,
      wind_speed: 9.7,
      wind_gusts: 22.3,
      wind_dir: 222,
    },
  ];
})();
